---
title: "TOWeR GHG microcosm experiment - Summer 2016"
author: "Gina Bledsoe"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: pdf_document
---

```{r set working directory}
rm(list=ls())
knitr::opts_knit$set(root.dir='C:/Users/annorion/Documents/_Projects/2016_Timberlake/sequences')
#knitr::knit("timberlake_microbes_4Sept2018.Rmd")
#list.files()
```

```{r load packages and functions }
getwd()

#Set source R tools
source("bin/DiversityFunctions.R")
source("bin/MothurTools.R")

#load req'd packages
require("vegan")
require("dplyr")
require("tidyverse")
require("nlme")
require("reshape2")
require("ecodist")
require("ggplot2")
require("ade4")
require("png")
require("MASS")
require("grid")
require("ape")
require("png")
require("picante")
require("phyloseq")
require("plyr")
require("VennDiagram")


#Set Std Err and Conf Int
se <- function(x, ...) {
  sd(x, na.rm = TRUE)/sqrt(length(na.omit(x)))
}
ci <- function(x, ...) {
  1.96 * sd(x, na.rm = TRUE)
}
```

```{r load data files and trim}
#Load data files
#Assign file names to variables
sharedfile = "TMG2016.unique_list.shared"
taxfile = "TMG2016.unique_list.0.03.cons.taxonomy"
metafile = "tmg_design.csv"


#head(meta)
#Read in OTU file
otu <- read.otu(sharedfile)
#tax <- read.tax(taxfile)
tax <- import_mothur(mothur_constaxonomy_file =  taxfile)
tax.df <- as.data.frame(tax)
colnames(tax.df)=c("Domain","Phylum","Class", "Order","Family","Genus")
tax <- tax_table(tax.df)
#tax

#Remove OTUs with less than 10 occurences across all sites
ncol(otu)
otu.2 <- otu[, which(colSums(otu) >= 2)]
ncol(otu.2)
#colnames(otu.2)
#rownames(otu.2)

#What sample has lowest read count? WRC15ECRP6M 16058
otu2<- colSums(t(otu.2))
otu2[which.min(colSums(t(otu.2)))]
otu2[which.max(colSums(t(otu.2)))]

#graph of read counts, need to work on display
c<-as.data.frame(otu.2)
c$colsum <- colSums(t(c))
c$group <- rownames(c)
p<-ggplot(c, aes(x=group,y=colsum))+geom_bar(stat="identity")
p
```

```{r with Field}
#Remove lowest sample and mock community
#colnames(otu.2)
#rownames(otu.2)
otu.2.no18PB <- otu.2[!(rownames(otu.2) %in% "18PB"),]
otu.2.no18PB <- otu.2.no18PB[!(rownames(otu.2.no18PB) %in% "MOCK"),]

#rownames(otu.2.no18PB)
#Now what is the lowest sample?
otu2[which.min(colSums(t(otu.2.no18PB)))]
 
#Subsample and rarefy
#What is difference between rrarefy and sample functions?
#Can set seed with sample()
otu.2 <- rrarefy(otu.2.no18PB, 38000)

otu2<- colSums(t(otu.2))
c<-as.data.frame(otu2)
c$colsum <- colSums(t(c))
c$group <- rownames(c)
p<-ggplot(c, aes(x=group,y=colsum))+geom_bar(stat="identity")+coord_flip()
p
```

```{r Relative abundance and PERMANOVA with Field}
#transforms read counts to relative abundance
otu.2.rel <- otu.2
for(i in 1:dim(otu.2)[1]){
  otu.2.rel[i,] <- otu.2[i,]/sum(otu.2[i,])
}

#Read in design file
meta <- read.csv(metafile)
#Combine meta data with relative abundance data

rownames(meta) <- meta$sample
meta <- meta[!(rownames(meta) %in% "18PB"),]
meta <- meta[!(rownames(meta) %in% "MOCK"),]

metaotu <- cbind(meta, otu.2.rel)
head(metaotu)
#Where does otu data begin, remove for PERMANOVA
#PERMANOVA with plant and Treatment as factors
metaotu.ad <- adonis(metaotu[,-c(1:10)] ~time+treatment*plant, method = "bray", data = metaotu, perm=1000, set.seed=42)
metaotu.ad 
```

```{r Calculate distance matrix and PCoA components with Field}

otu.2.rel.dist<-vegdist(otu.2.rel, method="bray")

# Principal Coordinates Analysis
otu.2.rel.dist.pcoa <- cmdscale(otu.2.rel.dist, k=3, eig=TRUE, add=FALSE)
# Classical (Metric) Multidimensional Scaling; returns PCoA coordinates
# eig=TRUE returns eigenvalues; k = # of dimensions to calculate

explainvar1a <- round(otu.2.rel.dist.pcoa$eig[1] / sum(otu.2.rel.dist.pcoa$eig), 3) * 100
explainvar2a <- round(otu.2.rel.dist.pcoa$eig[2] / sum(otu.2.rel.dist.pcoa$eig), 3) * 100
sum.eiga <- sum(explainvar1a, explainvar2a)

explainvar1a
explainvar2a


all.equal(rownames(meta), rownames(otu.2.rel))
# Set treatments
treat1 <- as.factor(meta$treatment)
droplevels(treat1)
#levels(treat1) <- ordered(c("s", "b", "c"))
treat2 <- as.factor(meta$time)
droplevels(treat2)
#levels(treat2) <- c("I","W","D")
treat3 <- as.factor(meta$plant)
droplevels(treat3)

pcoa.groups <- paste(meta$time, meta$treatment, meta$plant, sep = "_")

pcoa.points <- data.frame(otu.2.rel.dist.pcoa$points, group = pcoa.groups)

# Calculate Centroids (mean and SE)
pcoa.L.centroids <- melt(pcoa.points, id="group", measure.vars = c("X1", "X2"))
pcoa.centroids <- acast(pcoa.L.centroids, variable ~ group, mean)
pcoa.centroids.se <- acast(pcoa.L.centroids, variable ~ group, se)

pcoa.centroids.sd <- acast(pcoa.L.centroids, variable ~ group, sd)

# Combine
pcoa.cent.dataframe <- cbind(t(pcoa.centroids), t(pcoa.centroids.se))
colnames(pcoa.cent.dataframe) <- c("V1", "V2", "V1e", "V2e")
pcoa.cent.treats <- rownames(pcoa.cent.dataframe)

pcoa.col2 <- as.factor(sapply(strsplit(pcoa.cent.treats, "_"), `[`, 3))  # Plant
pcoa.col <- as.factor(sapply(strsplit(pcoa.cent.treats, "_"), `[`, 2)) # Treatment
pcoa.shape <- as.factor(sapply(strsplit(pcoa.cent.treats, "_"), `[`, 1))  # time

#pcoa.col <- ordered(c("Dry", "Interim", "Wet"))
pcoa.col <- ordered(pcoa.col, levels=c("D", "I", "W"))
pcoa.col <-revalue(pcoa.col, c("D"="Dry", "I"="Interim","W"="Wet"))
#pcoa.col <- mapvalues(pcoa.col, from = c("D", "I", "W"), to = c("Dry", "Interim", "Wet"))

#pcoa.col2 <- ordered(c("field", "-plant","+plant"))
pcoa.col2 <- ordered(pcoa.col2, levels=c("f", "n", "p"))
pcoa.col2 <-revalue(pcoa.col2, c("f"="field","n"="-plant","p"="+plant"))
#pcoa.col2 <- mapvalues(pcoa.col, from = c("f", "n", "p"), to = c("field", "-plant","+plant"))
              
#pcoa.shape <- ordered(c("A. virginicus", "Bulk Soil", "E. caroliniana"))
#pcoa.shape <- ordered(pcoa.shape,levels=c("bulk","av", "ec"))
#pcoa.shape <- revalue(pcoa.shape, c("bulk"="Bulk Soil", "av"="Grass", "ec"="Forb"))
#pcoa.shape <- mapvalues(pcoa.shape, from = c("bulk","av","ec"), to = c("Bulk Soil", "Grass", "Forb"))

##levels(pcoa.col) <- c("Control","Fertilized")
#set.seed(42)
##meta.env <- meta[,-c(1:8,10,12)]
##fit<-envfit(otu.2.rel.dist.pcoa$points, meta.env, perm=1000,na.rm=T, set.seed(1))
##A <-as.list(fit$vectors)
##vec<-as.data.frame(fit$vectors$arrows*sqrt(fit$vectors$r)*0.5)
##p<- as.data.frame(A$pvals)
##vec <- cbind(vec, p) 
##vec <-  subset(vec, A$pvals<=0.059)

##vec$parm<-rownames(vec)
##colnames(vec)

df1a <- as.data.frame(pcoa.cent.dataframe)
plot1 <- ggplot(df1a, aes(x=V1, y=V2, colour=pcoa.col, shape = pcoa.shape,
                 group = interaction(pcoa.col, pcoa.shape), colour=pcoa.col2)) + theme_bw() 

plot1 +  theme(panel.grid.major = element_blank(), 
               panel.grid.minor = element_blank()) + 
theme(panel.background = element_blank()) + 
  geom_point(aes(shape = pcoa.shape, colour = pcoa.col), size=8) +
  geom_point(aes(colour=pcoa.col2), size =4.0)+
  #geom_segment(data=vec, aes(x=0,xend=Dim1,y=0,yend=Dim2), size=2, 
      #arrow = arrow(length = unit(0.5, "cm")),colour="black",inherit.aes=F) + 
  #geom_text(data=vec,aes(x=Dim1,y=Dim2,label=vec$parm),size=5, inherit.aes=F, nudge_y = -.04) +
  geom_errorbarh(aes(xmax=V1+V1e, xmin=V1-V1e, height=0.01), colour="black") +    
  geom_errorbar(aes(ymax=V2+V2e, ymin=V2-V2e, width=0.01), colour="black") + 
  scale_colour_manual(values = c("#EB8F43", "#9BBB59","purple","red","yellow","blue","gray","pink","magenta")) +
  #"#EB8F43", "#9BBB59"
  #still having issue with scale rendering as desired
  scale_shape_manual(values = c(17,18,19,15)) +
  #coord_cartesian(xlim = c(-0.25, 0.3), ylim = c(-0.35, 0.3)) +
  theme(axis.title = element_text(size=18), axis.text=element_text(size=18), 
          axis.text.x = element_text(size=18),  axis.text.y = element_text(size=18),
          panel.border = element_rect(colour = "black", size=1.25)) +
  theme(axis.ticks.length=unit(0.3,"cm")) + 
  xlab("PCoA 1 (23.4%)") + ylab("PCoA 2 (17.3%)") + 
  labs(shape = "Time") +
  labs(colour="Treatment") +
  ggtitle("16S rRNA Microbial Community Analysis") + 
  theme(plot.title=element_text(size=10)) +
  theme(legend.text=element_text(size=10), legend.title = element_text(size=10))

ggsave("16SrRNA_TOWeRwithField.jpg", plot=last_plot(), device=NULL, path=NULL, scale=1, width=8.7, height=6.3, dpi=900, limitsize=TRUE)

```
```{r with out Field}
#Remove lowest sample  
#colnames(otu.2)
#rownames(otu.2)
otu.2.no18PB <- otu.2[!(rownames(otu.2) %in% "18PB"),]
otu.2.no18PB <- otu.2.no18PB[!(rownames(otu.2.no18PB) %in% "MOCK"),]
otu.2.no18PB <- otu.2.no18PB[!(rownames(otu.2.no18PB) %in% "TL1"),]
otu.2.no18PB <- otu.2.no18PB[!(rownames(otu.2.no18PB) %in% "TL2"),]
otu.2.no18PB <- otu.2.no18PB[!(rownames(otu.2.no18PB) %in% "TL3"),]
otu.2.no18PB <- otu.2.no18PB[!(rownames(otu.2.no18PB) %in% "TL4"),]
otu.2.no18PB <- otu.2.no18PB[!(rownames(otu.2.no18PB) %in% "TL5"),]
otu.2.no18PB <- otu.2.no18PB[!(rownames(otu.2.no18PB) %in% "TL6"),]
#rownames(otu.2.no18PB)
otu2[which.min(colSums(t(otu.2.no18PB)))]
#Now what is the lowest sample? 08NC  38747

#Subsample and rarefy
#What is difference between rrarefy and sample functions?
#Can set seed with sample()
otu.2 <- rrarefy(otu.2.no18PB, 38000)

otu2<- colSums(t(otu.2))
c<-as.data.frame(otu2)
c$colsum <- colSums(t(c))
c$group <- rownames(c)
p<-ggplot(c, aes(x=group,y=colsum))+geom_bar(stat="identity")+coord_flip()
p
```
```{r Relative abundance and PERMANOVA with out Field}
#transforms read counts to relative abundance
otu.2.rel <- otu.2
for(i in 1:dim(otu.2)[1]){
  otu.2.rel[i,] <- otu.2[i,]/sum(otu.2[i,])
}

#Read in design file
meta <- read.csv(metafile)
#Combine meta data with relative abundance data
#remove 18PB from meta, 
rownames(meta) <- meta$sample
meta <- meta[!(rownames(meta) %in% "18PB"),]
meta <- meta[!(rownames(meta) %in% "MOCK"),]
meta <- meta[!(rownames(meta) %in% "TL1"),]
meta <- meta[!(rownames(meta) %in% "TL2"),]
meta <- meta[!(rownames(meta) %in% "TL3"),]
meta <- meta[!(rownames(meta) %in% "TL4"),]
meta <- meta[!(rownames(meta) %in% "TL5"),]
meta <- meta[!(rownames(meta) %in% "TL6"),]
metaotu <- cbind(meta, otu.2.rel)
head(metaotu)
#Where does otu data begin, remove for PERMANOVA
#PERMANOVA with plant and Treatment as factors
metaotu.ad <- adonis(metaotu[,-c(1:10)] ~time + treatment * plant, method = "bray", data = metaotu, perm=1000, set.seed=42)
metaotu.ad 
```
```{r Calculate distance matrix and PCoA components with out Field}

otu.2.rel.dist<-vegdist(otu.2.rel, method="bray")

# Principal Coordinates Analysis
otu.2.rel.dist.pcoa <- cmdscale(otu.2.rel.dist, k=3, eig=TRUE, add=FALSE)
# Classical (Metric) Multidimensional Scaling; returns PCoA coordinates
# eig=TRUE returns eigenvalues; k = # of dimensions to calculate

explainvar1a <- round(otu.2.rel.dist.pcoa$eig[1] / sum(otu.2.rel.dist.pcoa$eig), 3) * 100
explainvar2a <- round(otu.2.rel.dist.pcoa$eig[2] / sum(otu.2.rel.dist.pcoa$eig), 3) * 100
sum.eiga <- sum(explainvar1a, explainvar2a)

explainvar1a
explainvar2a


all.equal(rownames(meta), rownames(otu.2.rel))
# Set treatments
treat1 <- as.factor(meta$treatment)
droplevels(treat1)
#levels(treat1) <- ordered(c("s", "b", "c"))
treat2 <- as.factor(meta$time)
droplevels(treat2)
#levels(treat2) <- c("I","W","D")
treat3 <- as.factor(meta$plant)
droplevels(treat3)

pcoa.groups <- paste(meta$time, meta$treatment, meta$plant, sep = "_")

pcoa.points <- data.frame(otu.2.rel.dist.pcoa$points, group = pcoa.groups)

# Calculate Centroids (mean and SE)
pcoa.L.centroids <- melt(pcoa.points, id="group", measure.vars = c("X1", "X2"))
pcoa.centroids <- acast(pcoa.L.centroids, variable ~ group, mean)
pcoa.centroids.se <- acast(pcoa.L.centroids, variable ~ group, se)

pcoa.centroids.sd <- acast(pcoa.L.centroids, variable ~ group, sd)

# Combine
pcoa.cent.dataframe <- cbind(t(pcoa.centroids), t(pcoa.centroids.se))
colnames(pcoa.cent.dataframe) <- c("V1", "V2", "V1e", "V2e")
pcoa.cent.treats <- rownames(pcoa.cent.dataframe)

pcoa.col2 <- as.factor(sapply(strsplit(pcoa.cent.treats, "_"), `[`, 3))  # Plant
pcoa.col <- as.factor(sapply(strsplit(pcoa.cent.treats, "_"), `[`, 2)) # Treatment
pcoa.shape <- as.factor(sapply(strsplit(pcoa.cent.treats, "_"), `[`, 1))  # Plant

#pcoa.col <- ordered(c("Dry", "Interim", "Wet"))
pcoa.col <- ordered(pcoa.col, levels=c("D", "I", "W"))
pcoa.col <-revalue(pcoa.col, c("D"="Dry", "I"="Interim","W"="Wet"))
#pcoa.col <- mapvalues(pcoa.col, from = c("D", "I", "W"), to = c("Dry", "Interim", "Wet"))

#pcoa.col2 <- ordered(c("field", "-plant","+plant"))
pcoa.col2 <- ordered(pcoa.col2, levels=c("f", "n", "p"))
pcoa.col2 <-revalue(pcoa.col2, c("f"="field","n"="-plant","p"="+plant"))
#pcoa.col2 <- mapvalues(pcoa.col, from = c("f", "n", "p"), to = c("field", "-plant","+plant"))

##levels(pcoa.col) <- c("Control","Fertilized")
#set.seed(42)
##meta.env <- meta[,-c(1:8,10,12)]
##fit<-envfit(otu.2.rel.dist.pcoa$points, meta.env, perm=1000,na.rm=T, set.seed(1))
##A <-as.list(fit$vectors)
##vec<-as.data.frame(fit$vectors$arrows*sqrt(fit$vectors$r)*0.5)
##p<- as.data.frame(A$pvals)
##vec <- cbind(vec, p) 
##vec <-  subset(vec, A$pvals<=0.059)

##vec$parm<-rownames(vec)
##colnames(vec)

df1a <- as.data.frame(pcoa.cent.dataframe)
plot1 <- ggplot(df1a, aes(x=V1, y=V2, colour=pcoa.col, shape = pcoa.shape,
                 group = interaction(pcoa.col, pcoa.shape), colour=pcoa.col2)) + theme_bw() 

plot1 +  theme(panel.grid.major = element_blank(), 
               panel.grid.minor = element_blank()) + 
theme(panel.background = element_blank()) + 
  geom_point(aes(shape = pcoa.shape, colour = pcoa.col), size=8) +
  geom_point(aes(colour=pcoa.col2), size =4.0)+
  #geom_segment(data=vec, aes(x=0,xend=Dim1,y=0,yend=Dim2), size=2, 
      #arrow = arrow(length = unit(0.5, "cm")),colour="black",inherit.aes=F) + 
  #geom_text(data=vec,aes(x=Dim1,y=Dim2,label=vec$parm),size=5, inherit.aes=F, nudge_y = -.04) +
  geom_errorbarh(aes(xmax=V1+V1e, xmin=V1-V1e, height=0.01), colour="black") +    
  geom_errorbar(aes(ymax=V2+V2e, ymin=V2-V2e, width=0.01), colour="black") + 
  scale_colour_manual(values = c("#EB8F43", "#9BBB59","purple","red","yellow","blue","gray","pink","magenta")) +
  #"#EB8F43", "#9BBB59"
  #still having issue with scale rendering as desired
  scale_shape_manual(values = c(17,18,19,15)) +
  #coord_cartesian(xlim = c(-0.25, 0.3), ylim = c(-0.35, 0.3)) +
  theme(axis.title = element_text(size=18), axis.text=element_text(size=18), 
          axis.text.x = element_text(size=18),  axis.text.y = element_text(size=18),
          panel.border = element_rect(colour = "black", size=1.25)) +
  theme(axis.ticks.length=unit(0.3,"cm")) + 
  xlab("PCoA 1 (23.4%)") + ylab("PCoA 2 (17.3%)") + 
  labs(shape = "Soil Source") +
  labs(colour="Treatment") +
  ggtitle("16S rRNA Microbial Community Analysis") + 
  theme(plot.title=element_text(size=10)) +
  theme(legend.text=element_text(size=10), legend.title = element_text(size=10))

ggsave("16SrRNA_WRC2015Rhizo.jpg", plot=last_plot(), device=NULL, path=NULL, scale=1, width=8.7, height=6.3, dpi=900, limitsize=TRUE)

```