---
title: "Greenhouse gas flux linear mixed effects models"
author: "Colin G. Finlay"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    df_print: paged
---
# Setup

```{r setup, include=FALSE}
rm(list=ls())
knitr::opts_chunk$set(echo = FALSE, warning=FALSE)
#use to set working directory 
knitr::opts_knit$set(root.dir="~/GitHub/WetlandMesocosm_GHG_Timberlake/analyses")
```

# Load packages and functions

```{r load packages and functions, include FALSE }
require("tidyverse")
require("MuMIn")
require("AICcmodavg")
require("emmeans")
require("lme4")
require("gasfluxes")
require("rstatix")
require("ggpubr")
require("lattice")
require("car")
```


```{r Standard error and confidence intervals}
#Set Std Err and Conf Int
se <- function(x, ...) {
  sd(x, na.rm = TRUE)/sqrt(length(na.omit(x)))
}
ci <- function(x, ...) {
  1.96 * sd(x, na.rm = TRUE)
}
```

# Load files

```{r load files paths}
#Load data files
#Assign file names to variables
metafile = "../data/tmg_design.csv"
```

```{r read in meta data}
#Read in design file
meta <- read.csv(metafile)

#Remove mock, field, and box samples. 
rownames(meta) <- meta$sample
meta <- meta[!(rownames(meta) %in% "MOCK"),]
meta <- meta[!(rownames(meta) %in% "TL1"),]
meta <- meta[!(rownames(meta) %in% "TL2"),]
meta <- meta[!(rownames(meta) %in% "TL3"),]
meta <- meta[!(rownames(meta) %in% "TL4"),]
meta <- meta[!(rownames(meta) %in% "TL5"),]
meta <- meta[!(rownames(meta) %in% "TL6"),]
meta <- meta[!(meta$source %in% "b"),]
meta <- meta[!(meta$source %in% "s"),]
```

## Wrangling, flux calculation, assumption testing

```{r GHG wrangling}
# Version of ghg with labels for T1 through T4 analysis:
ghg2 <- read.csv("../data/TMG_GHG-Flux_Pub_3.csv", header=TRUE)

# FIX c2o TYPO IN ghg2:
colnames(ghg2)[18] <- "co2_ppm"

# ghg2, select T1 through T4, and all ppm measurements:
ghg_ppm <- ghg2 %>%
  dplyr::select('date', 'chamber', 'timepoint', 'plant', 'ch4_ppm', 'co2_ppm', 'n2o_ppm')%>%
  dplyr::filter(date !='7/24/2016')

# Set factors:
ghg_ppm$chamber <- as.factor(ghg_ppm$chamber)
ghg_ppm$date <- as.factor(ghg_ppm$date)

# Change design$box to design$chamber in order to join with ghg$chamber
colnames(meta)[2] <- "chamber"

# Add on meta data
ghg_ppm <- ghg_ppm %>%
  left_join(meta[,-c(3, 4, 7, 8, 9)], by="chamber")

# Add new date column, to shorten:
ghg_ppm$date_short <- ghg_ppm$date
# remove "/2016" from date_short:
ghg_ppm$date_short <- str_remove(ghg_ppm$date_short, "/2016")
```

```{r Calculate T0s from WRC static chamber monitoring}
# Will use results from monthly WRC static chamber to calculate average T0. Then calculate fluxes from TMG mesocosms.

# read in compiled T0 data:
WRC_T0s <- read.csv("../data/WRC_T0s_for_TMG_ambient_calculation.csv")

# Set Sample_Date as factor:
WRC_T0s$Sample_Date <- as.factor(WRC_T0s$Sample_Date)

# calculate averages within each month:
CO2_T0_monthly_avg <- aggregate(T0_CO2_ppm ~ Sample_Date, data = WRC_T0s, FUN = mean, na.rm = TRUE)
CH4_T0_monthly_avg <- aggregate(T0_CH4_ppm ~ Sample_Date, data = WRC_T0s, FUN = mean, na.rm = TRUE)
N2O_T0_monthly_avg <- aggregate(T0_N2O_ppm ~ Sample_Date, data = WRC_T0s, FUN = mean, na.rm = TRUE)

# Average the two years of August data:
CO2_T0_monthly_avg[nrow(CO2_T0_monthly_avg)+1, "T0_CO2_ppm"] <- mean(c(CO2_T0_monthly_avg[1, "T0_CO2_ppm"], CO2_T0_monthly_avg[2, "T0_CO2_ppm"]), na.rm = TRUE)

CH4_T0_monthly_avg[nrow(CH4_T0_monthly_avg)+1, "T0_CH4_ppm"] <- mean(c(CH4_T0_monthly_avg[1, "T0_CH4_ppm"], CH4_T0_monthly_avg[2, "T0_CH4_ppm"]), na.rm = TRUE)

N2O_T0_monthly_avg[nrow(N2O_T0_monthly_avg)+1, "T0_N2O_ppm"] <- mean(c(N2O_T0_monthly_avg[1, "T0_N2O_ppm"], N2O_T0_monthly_avg[2, "T0_N2O_ppm"]), na.rm = TRUE)

# Add in the name:
CO2_T0_monthly_avg$Sample_Date <- factor(c("Aug_2022", "August_2021", "Jul_2022", "June_2022", "August_21_22"))
CH4_T0_monthly_avg$Sample_Date <- factor(c("Aug_2022", "August_2021", "Jul_2022", "June_2022", "August_21_22"))
N2O_T0_monthly_avg$Sample_Date <- factor(c("Aug_2022", "August_2021", "Jul_2022", "June_2022", "August_21_22"))
```

```{r wrangle T0 averages for flux calculation}
# bind together the three GHGs:
T0_averages_combined <- CH4_T0_monthly_avg %>%
  cbind(CO2_T0_monthly_avg$T0_CO2_ppm) %>%
  cbind(N2O_T0_monthly_avg$T0_N2O_ppm)

# drop the two August monthly:
T0_averages_combined <- T0_averages_combined[3:5,]

# Rename 'Sample_Date' in T0_averages_combined to 'date' to match the 'ghg_flux' column
colnames(T0_averages_combined)[1] <- "date"

# Add chamber as NAs:
T0_averages_combined$chamber <- NA

# Rename GHG columns to match ghg_flux:
colnames(T0_averages_combined)[2:4] <- c("ch4_ppm", "co2_ppm", "n2o_ppm")

# Add time columns to match ghg_flux:
T0_averages_combined$time_min <- 0
T0_averages_combined$time <- 0

# Add month column:
T0_averages_combined$month <- c("July", "June", "August")
```

```{r GHG flux wrangling}
# Format a data frame for 'gasfluxes' package:
ghg_flux <- ghg2[,c(1:2, 12, 15:19)]

# Remove 7/24/2016 from data frame, as per Gina's advice
ghg_flux <- ghg_flux %>%
  dplyr::filter(date !='7/24/2016')

# Combine 'date' and 'chamber' strings to create a unique ID:
ghg_flux$ID <- paste(ghg_flux$date, ghg_flux$chamber)

# convert Volume (cm^3) to Volume (m^3):
ghg_flux$V <- (ghg_flux$Vol..cm3. * (1/1e+06))

# Copy 'Area..m2.' to a new column named 'A':
ghg_flux$A <- ghg_flux$Area..m2.

# Convert time in minutes to time in hours:
ghg_flux$time <- (ghg_flux$time_min * (1/60))

# Data frame to bind T0s from WRC:
ghg_flux_w_T0 <- ghg_flux

# Add in month column that takes date strings and matches them to "July", "June", "August":
# Create a vector of month names
month_names <- c("January", "February", "March", "April", "May", "June",
                 "July", "August", "September", "October", "November", "December")

# Extract the month as a number and convert it to a month name
ghg_flux_w_T0 <- ghg_flux_w_T0 %>%
  mutate(
    month = month_names[as.numeric(substr(date, 1, 1))]
  )

# Copy July and June rows because there are two July and June sampling dates:
T0_averages_combined <- rbind(T0_averages_combined, T0_averages_combined[1,])
T0_averages_combined <- rbind(T0_averages_combined, T0_averages_combined[2,])

# Add TMG-style dates to match with ghg_flux:
T0_averages_combined$date_TMG <- c("7/11/2016", "6/13/2016", "8/11/2016", "7/25/2016", "6/28/2016")

# For loop:
for (unique_date in unique(ghg_flux_w_T0$date)) {
  for (unique_chamber in unique(ghg_flux_w_T0$chamber)) {
    
    # Filter the monthly average corresponding to the current date
    month_avg <- T0_averages_combined %>% filter(date_TMG == unique_date)
    
    # Skip if there is no corresponding monthly average for the date
    if (nrow(month_avg) == 0) next
    
    # Create a new row with time = 0 and the averages for the current date and chamber
    new_row <- data.frame(
      date = unique_date,
      chamber = unique_chamber,
      time = month_avg$time,
      time_min = month_avg$time_min,
      ch4_ppm = month_avg$ch4_ppm,
      co2_ppm = month_avg$co2_ppm,
      n2o_ppm = month_avg$n2o_ppm,
      month = month_avg$month
    )
    
    # Bind the new row to ghg_flux
    ghg_flux_w_T0 <- bind_rows(ghg_flux_w_T0, new_row)
  }
}

# Reorder rows by date, chamber, and time:
ghg_flux_w_T0 <- ghg_flux_w_T0 %>%
  arrange(date, chamber, time)

# Copy some of rows following T0s onto T0s (ID, V, A):
# Define the columns with missing values to be filled from the row below
columns_to_fill <- c("ID", "V", "A")

# Loop through the rows from the bottom to the top to fill missing values from the row below
for (i in (nrow(ghg_flux_w_T0) - 1):1) {
  # Check for missing values in the specified columns
  missing_values <- is.na(ghg_flux_w_T0[i, columns_to_fill])
  
  # If there are missing values, copy the values from the row below
  if (any(missing_values)) {
    ghg_flux_w_T0[i, columns_to_fill][missing_values] <- ghg_flux_w_T0[i + 1, columns_to_fill][missing_values]
  }
}



# Convert ppm to mg/m^3, based on https://www.cdc.gov/niosh/docs/2004-101/calc.html (based on 25°C and 1 atm):
# y mg/m3 = (x ppm)(molar mass)/24.45
  # 24.45 is the volume (liters) of a mole (gram molecular weight) of a gas or vapor when the pressure is at 1 atmosphere (760 torr or 760 mm Hg) and at 25°C

# CH4 mg/m3
# C is the package 'gasfluxes' abbreviation for concentration. 16.04 g/mol = molar mass of CH4
ghg_flux_w_T0$C_ch4 <- ((ghg_flux_w_T0$ch4_ppm * 16.04)/24.45)

# CO2 mg/m3
# molar mass of CO2 = 44.01 g/mol
ghg_flux_w_T0$C_co2 <- ((ghg_flux_w_T0$co2_ppm * 44.01)/24.45)

# N2O mg/m3
# molar mass of N2O = 44.013 g/mol
ghg_flux_w_T0$C_n2o <-  ((ghg_flux_w_T0$n2o_ppm * 44.013)/24.45)

# Split off data frames for each greenhouse gas:
ch4_flux_input_w_T0 <- ghg_flux_w_T0[,c(9:12, 14)]

co2_flux_input_w_T0 <- ghg_flux_w_T0[,c(9:12, 15)]

n2o_flux_input_w_T0 <- ghg_flux_w_T0[,c(9:12, 16)]

# Rename C_ghg columns to 'C':
colnames(ch4_flux_input_w_T0)[5] <- "C"

colnames(co2_flux_input_w_T0)[5] <- "C"

colnames(n2o_flux_input_w_T0)[5] <- "C"

# Must omit NAs before using gasfluxes():
ch4_flux_input_w_T0 <- na.omit(ch4_flux_input_w_T0)

co2_flux_input_w_T0 <- na.omit(co2_flux_input_w_T0)

# n2o_flux_input has negative values, will need to be converted to NAs, then all NAs omitted
n2o_flux_input_w_T0$C[n2o_flux_input_w_T0$C<0] <- NA
n2o_flux_input_w_T0 <- na.omit(n2o_flux_input_w_T0)
```

```{r Make T0 flux dataframes' V and A numeric}
ch4_flux_input_w_T0$V <- as.numeric(ch4_flux_input_w_T0$V)
ch4_flux_input_w_T0$A <- as.numeric(ch4_flux_input_w_T0$A)

co2_flux_input_w_T0$V <- as.numeric(co2_flux_input_w_T0$V)
co2_flux_input_w_T0$A <- as.numeric(co2_flux_input_w_T0$A)

n2o_flux_input_w_T0$V <- as.numeric(n2o_flux_input_w_T0$V)
n2o_flux_input_w_T0$A <- as.numeric(n2o_flux_input_w_T0$A)
```

```{r GHG flux calculation}
ch4_flux.results_w_T0 <- gasfluxes(ch4_flux_input_w_T0, method = c("linear","robust linear", "HMR"), plot = T)
co2_flux.results_w_T0 <- gasfluxes(co2_flux_input_w_T0, method = c("linear","robust linear", "HMR"), plot = T)
n2o_flux.results_w_T0 <- gasfluxes(n2o_flux_input_w_T0, method = c("linear","robust linear", "HMR"), plot = T)
```

```{r GHG flux results wrangling}
# If HMR is available, use HMR
# If HMR is not available, use robust linear
# If robust linear is not available use linear

# New DF with all three f0s:
ch4_fluxes_only_w_T0 <- ch4_flux.results_w_T0[,c(1:2, 11, 17)]
co2_fluxes_only_w_T0 <- co2_flux.results_w_T0[,c(1:2, 11, 17)]
n2o_fluxes_only_w_T0 <- n2o_flux.results_w_T0[,c(1:2, 11, 17)]

# New column for final flux selection:
ch4_fluxes_only_w_T0$f0_selected <- ch4_fluxes_only_w_T0$HMR.f0
co2_fluxes_only_w_T0$f0_selected <- co2_fluxes_only_w_T0$HMR.f0
n2o_fluxes_only_w_T0$f0_selected <- n2o_flux.results_w_T0$HMR.f0

# Where HMR = NA, replace with the robust linear value:
ch4_fluxes_only_w_T0$f0_selected[na.action(na.omit(ch4_fluxes_only_w_T0$HMR.f0))] <- ch4_fluxes_only_w_T0$robust.linear.f0[na.action(na.omit(ch4_fluxes_only_w_T0$HMR.f0))]

co2_fluxes_only_w_T0$f0_selected[na.action(na.omit(co2_fluxes_only_w_T0$HMR.f0))] <- co2_fluxes_only_w_T0$robust.linear.f0[na.action(na.omit(co2_fluxes_only_w_T0$HMR.f0))]

n2o_fluxes_only_w_T0$f0_selected[na.action(na.omit(n2o_fluxes_only_w_T0$HMR.f0))] <- n2o_fluxes_only_w_T0$robust.linear.f0[na.action(na.omit(n2o_fluxes_only_w_T0$HMR.f0))]

# Where f0_selected still has NAs, replace with the linear.f0:
ch4_fluxes_only_w_T0$f0_selected[na.action(na.omit(ch4_fluxes_only_w_T0$f0_selected))] <- ch4_fluxes_only_w_T0$linear.f0[na.action(na.omit(ch4_fluxes_only_w_T0$f0_selected))]

co2_fluxes_only_w_T0$f0_selected[na.action(na.omit(co2_fluxes_only_w_T0$f0_selected))] <- co2_fluxes_only_w_T0$linear.f0[na.action(na.omit(co2_fluxes_only_w_T0$f0_selected))]

n2o_fluxes_only_w_T0$f0_selected[na.action(na.omit(n2o_fluxes_only_w_T0$f0_selected))] <- n2o_fluxes_only_w_T0$linear.f0[na.action(na.omit(n2o_fluxes_only_w_T0$f0_selected))]

# Combine separate DFs back into one DF for statistics
# start with CH4 IDs and f0 for a base dataframe
select_fluxes_combined_w_T0 <- ch4_fluxes_only_w_T0[,c(1,5)]

# rename to distinguish between GHGs
colnames(select_fluxes_combined_w_T0)[2] <- "f0_CH4"

# add on CO2 fluxes
select_fluxes_combined_w_T0$f0_CO2 <- co2_fluxes_only_w_T0$f0_selected

# add on N2O fluxes
select_fluxes_combined_w_T0$f0_N2O <- n2o_fluxes_only_w_T0$f0_selected

# Character vector with correct sample ID order:
Order_GHG_flux <-   c("6/13/2016 1N", "6/13/2016 1P", "6/13/2016 2N", "6/13/2016 2P", "6/13/2016 3N", "6/13/2016 3P", "6/13/2016 4N", "6/13/2016 4P", "6/13/2016 5N", "6/13/2016 5P", "6/13/2016 6N", "6/13/2016 6P", "6/13/2016 7N", "6/13/2016 7P", "6/13/2016 8N", "6/13/2016 8P", "6/13/2016 9N", "6/13/2016 9P", "6/13/2016 10N", "6/13/2016 10P", "6/13/2016 11N", "6/13/2016 11P", "6/13/2016 12N", "6/13/2016 12P", "6/13/2016 13N", "6/13/2016 13P", "6/13/2016 14N", "6/13/2016 14P", "6/13/2016 15N", "6/13/2016 15P", "6/13/2016 16N", "6/13/2016 16P", "6/13/2016 17N", "6/13/2016 17P", "6/13/2016 18N", "6/13/2016 18P", "6/28/2016 1N", "6/28/2016 1P", "6/28/2016 2N", "6/28/2016 2P", "6/28/2016 3N", "6/28/2016 3P", "6/28/2016 4N", "6/28/2016 4P", "6/28/2016 5N", "6/28/2016 5P", "6/28/2016 6N", "6/28/2016 6P", "6/28/2016 7N", "6/28/2016 7P", "6/28/2016 8N", "6/28/2016 8P", "6/28/2016 9N", "6/28/2016 9P", "6/28/2016 10N", "6/28/2016 10P", "6/28/2016 11N", "6/28/2016 11P", "6/28/2016 12N", "6/28/2016 12P", "6/28/2016 13N", "6/28/2016 13P", "6/28/2016 14N", "6/28/2016 14P", "6/28/2016 15N", "6/28/2016 15P", "6/28/2016 16N", "6/28/2016 16P", "6/28/2016 17N", "6/28/2016 17P", "6/28/2016 18N", "6/28/2016 18P", "7/11/2016 1N", "7/11/2016 1P", "7/11/2016 2N", "7/11/2016 2P", "7/11/2016 3N", "7/11/2016 3P", "7/11/2016 4N", "7/11/2016 4P", "7/11/2016 5N", "7/11/2016 5P", "7/11/2016 6N", "7/11/2016 6P", "7/11/2016 7N", "7/11/2016 7P", "7/11/2016 8N", "7/11/2016 8P", "7/11/2016 9N", "7/11/2016 9P", "7/11/2016 10N", "7/11/2016 10P", "7/11/2016 11N", "7/11/2016 11P", "7/11/2016 12N", "7/11/2016 12P", "7/11/2016 13N", "7/11/2016 13P", "7/11/2016 14N", "7/11/2016 14P", "7/11/2016 15N", "7/11/2016 15P", "7/11/2016 16N", "7/11/2016 16P", "7/11/2016 17N", "7/11/2016 17P", "7/11/2016 18N", "7/11/2016 18P", "7/25/2016 1N", "7/25/2016 1P", "7/25/2016 2N", "7/25/2016 2P", "7/25/2016 3N", "7/25/2016 3P", "7/25/2016 4N", "7/25/2016 4P", "7/25/2016 5N", "7/25/2016 5P", "7/25/2016 6N", "7/25/2016 6P", "7/25/2016 7N", "7/25/2016 7P", "7/25/2016 8N", "7/25/2016 8P", "7/25/2016 9N", "7/25/2016 9P", "7/25/2016 10N", "7/25/2016 10P", "7/25/2016 11N", "7/25/2016 11P", "7/25/2016 12N", "7/25/2016 12P", "7/25/2016 13N", "7/25/2016 13P", "7/25/2016 14N", "7/25/2016 14P", "7/25/2016 15N", "7/25/2016 15P", "7/25/2016 16N", "7/25/2016 16P", "7/25/2016 17N", "7/25/2016 17P", "7/25/2016 18N", "7/25/2016 18P", "8/11/2016 1N", "8/11/2016 1P", "8/11/2016 2N", "8/11/2016 2P", "8/11/2016 3N", "8/11/2016 3P", "8/11/2016 4N", "8/11/2016 4P", "8/11/2016 5N", "8/11/2016 5P", "8/11/2016 6N", "8/11/2016 6P", "8/11/2016 7N", "8/11/2016 7P", "8/11/2016 8N", "8/11/2016 8P", "8/11/2016 9N", "8/11/2016 9P", "8/11/2016 10N", "8/11/2016 10P", "8/11/2016 11N", "8/11/2016 11P", "8/11/2016 12N", "8/11/2016 12P", "8/11/2016 13N", "8/11/2016 13P", "8/11/2016 14N", "8/11/2016 14P", "8/11/2016 15N", "8/11/2016 15P", "8/11/2016 16N", "8/11/2016 16P", "8/11/2016 17N", "8/11/2016 17P", "8/11/2016 18N", "8/11/2016 18P")

# Change order of select_fluxes_combined_w_T0 to match the other dataframes
select_fluxes_combined_w_T0 <- select_fluxes_combined_w_T0[match(Order_GHG_flux, select_fluxes_combined_w_T0$ID), ]

# CHECK ROW ORDERS NOW

# DF that contains meta info and same row number as select_fluxes_combined_w_T0
ghg_ppm_filtered <- ghg_ppm %>%
  dplyr::filter(timepoint == "T1")

# Add date_short back onto DFs for plotting
select_fluxes_combined_w_T0$date_short <- ghg_ppm_filtered$date_short

# Add on 'plant'
select_fluxes_combined_w_T0$plant <- ghg_ppm_filtered$plant

# Add on 'treatment'
select_fluxes_combined_w_T0$treatment <- ghg_ppm_filtered$treatment

# Add on 'history'
select_fluxes_combined_w_T0$history <- ghg_ppm_filtered$history
```

```{r set factors}
# Make sure factors are factors: 
ghg_ppm_filtered$chamber <- as.factor(ghg_ppm_filtered$chamber)

select_fluxes_combined_w_T0$chamber <- ghg_ppm_filtered$chamber
select_fluxes_combined_w_T0$date_short <- as.factor(select_fluxes_combined_w_T0$date_short)
select_fluxes_combined_w_T0$plant <- as.factor(select_fluxes_combined_w_T0$plant)
select_fluxes_combined_w_T0$treatment <- as.factor(select_fluxes_combined_w_T0$treatment)
select_fluxes_combined_w_T0$history <- as.factor(select_fluxes_combined_w_T0$history)
```

```{r assumption testing: outliers}
# CH4
Outliers_f0_CH4_w_T0 <- select_fluxes_combined_w_T0 %>%
  group_by(date_short) %>%
  identify_outliers(f0_CH4)
Outliers_f0_CH4_w_T0
  # There are extreme outliers.

# CO2
Outliers_f0_CO2_w_T0 <- select_fluxes_combined_w_T0 %>%
  group_by(date_short) %>%
  identify_outliers(f0_CO2)
Outliers_f0_CO2_w_T0
  # There are extreme outliers.

# N2O
Outliers_f0_N2O_w_T0 <- select_fluxes_combined_w_T0 %>%
  group_by(date_short) %>%
  identify_outliers(f0_N2O)
Outliers_f0_N2O_w_T0
  # There are extreme outliers.
```
  
```{r assumption testing: normality}
# CH4
select_fluxes_combined_w_T0 %>%
  group_by(date_short) %>%
  shapiro_test(f0_CH4)
  # Not normally distributed

  # QQ plot:
ggqqplot(select_fluxes_combined_w_T0, "f0_CH4", facet.by = "date_short")


# CO2
select_fluxes_combined_w_T0 %>%
  group_by(date_short) %>%
  shapiro_test(f0_CO2)
  # Not normally distributed

  # QQ plot:
ggqqplot(select_fluxes_combined_w_T0, "f0_CO2", facet.by = "date_short")

# N2O
select_fluxes_combined_w_T0 %>%
  group_by(date_short) %>%
  shapiro_test(f0_N2O)
  # Not normally distributed

  # QQ plot:
ggqqplot(select_fluxes_combined_w_T0, "f0_N2O", facet.by = "date_short")
```
# Mixed-effects modeling

```{r lme4 example to test}
data(Orthodont,package="nlme")
Orthodont$nsex <- as.numeric(Orthodont$Sex=="Male")
Orthodont$nsexage <- with(Orthodont, nsex*age)
lmer(distance ~ age + (age|Subject) + (0+nsex|Subject) +
     (0 + nsexage|Subject), data=Orthodont)
```

```{r CH4 PPM hyposthesis testing}
ch4.lm1 <- lmer(f0_CH4 ~ (1|date_short) + (1|chamber) , data=select_fluxes_combined_w_T0, REML=FALSE)

ch4.lm2 <- lmer(f0_CH4~treatment + (1|date_short) + (1|chamber), data=select_fluxes_combined_w_T0, REML=FALSE)

ch4.lm3 <- lmer(f0_CH4~plant + (1|date_short) + (1|chamber), data=select_fluxes_combined_w_T0, REML=FALSE)

ch4.lm4 <- lmer(f0_CH4~treatment * plant + (1|date_short) + (1|chamber), data=select_fluxes_combined_w_T0, REML=FALSE)

ch4.lm5 <- lmer(f0_CH4~ history + plant + (1|date_short) + (1|chamber), data=select_fluxes_combined_w_T0, REML=FALSE)

#ch4.lm6 <- lmer(f0_CH4 ~ (1|chamber) , data=select_fluxes_combined_w_T0, REML=FALSE)

#ch4.lm7 <- lmer(f0_CH4 ~ (1|date_short), data=select_fluxes_combined_w_T0, REML=FALSE)

ch4.lm8 <- lmer(f0_CH4~ plant + treatment + history + (1|date_short) + (1|chamber), data=select_fluxes_combined_w_T0, REML=FALSE)

ch4.lm9 <- lmer(f0_CH4~ history + (1|date_short) + (1|chamber), data=select_fluxes_combined_w_T0, REML=FALSE)

ch4.lm10 <- lmer(f0_CH4~ plant + treatment + (1|date_short) + (1|chamber), data=select_fluxes_combined_w_T0, REML=FALSE)

ch4.lm11 <- lmer(f0_CH4~ plant * history + (1|date_short) + (1|chamber), data=select_fluxes_combined_w_T0, REML=FALSE)

ch4.lm12 <- lmer(f0_CH4~ treatment + history + (1|date_short) + (1|chamber), data=select_fluxes_combined_w_T0, REML=FALSE)

#This is a likelihood ratio test to get Chi squared value and p-value
##a <- anova(ch4.lm1, ch4.lm2, ch4.lm3,ch4.lm4,ch4.lm5, ch4.lm6, ch4.lm7, ch4.lm8, ch4.lm9, ch4.lm4a, ch4.lm7a, ch4.lm8a)
##a
##anova(ch4.lm6)

#AIC weights
c.mod <- list(ch4.lm1, ch4.lm2, ch4.lm3,ch4.lm4,ch4.lm5, ch4.lm8, ch4.lm9, ch4.lm10, ch4.lm11, ch4.lm12)
Modnames <- c("null", "treatment", "plant", "T*P", "H+P", "P+T+H", "H", "P+T", "P*H", "T+H")
ch4_LME_RES <- aictab(cand.set = c.mod, modnames = Modnames, second.ord = TRUE)

#Gas ID for merging
ch4_LME_RES$GHG <- "CH4"

#Variance explained by fixed effects and the entire model
r.squaredGLMM(ch4.lm1) #null
r.squaredGLMM(ch4.lm2) #treatment
r.squaredGLMM(ch4.lm3) #plant
r.squaredGLMM(ch4.lm4) #t*p
r.squaredGLMM(ch4.lm5) #h + p
r.squaredGLMM(ch4.lm8) #p+t+h
r.squaredGLMM(ch4.lm9) #h
r.squaredGLMM(ch4.lm10)#p+t
r.squaredGLMM(ch4.lm11)#p*h
r.squaredGLMM(ch4.lm12)#t+h

summary(ch4.lm8, ddf="Kenward-Roger")
confint.merMod(ch4.lm8, oldNames = FALSE)
p=profile(ch4.lm8)
xyplot(p)
densityplot(p)
qqPlot(resid(ch4.lm8), main="QQ Plot")
shapiro.test(resid(ch4.lm8))

#Interaction not significant so did not run post hoc
#Post hoc Tests
#Estimated marginal means - similar to lsmeans, uses t distribution
#https://cran.rstudio.com/web/packages/emmeans/vignettes/interactions.html

 emm <- emmeans(ch4.lm8, ~ treatment , adjust = "sidak")
 pairs(emm)
 multcomp::cld(emm, Letters=letters)
 
 emm <- emmeans(ch4.lm8, ~ history , adjust = "sidak")
 pairs(emm)
 multcomp::cld(emm, Letters=letters)
 
 emm <- emmeans(ch4.lm8, ~ plant , adjust = "sidak")
 pairs(emm)
 multcomp::cld(emm, Letters=letters)
  #p <-contrast(emm, "consec", simple="each", combine =TRUE, adjust="mvt")
  #p
```

```{r co2 PPM hypothesis testing}
co2.lm1 <- lmer(f0_CO2 ~ (1|date_short) + (1|chamber) , data=select_fluxes_combined_w_T0, REML=FALSE)

co2.lm2 <- lmer(f0_CO2~treatment + (1|date_short) + (1|chamber), data=select_fluxes_combined_w_T0, REML=FALSE)

co2.lm3 <- lmer(f0_CO2~plant + (1|date_short) + (1|chamber), data=select_fluxes_combined_w_T0, REML=FALSE)

co2.lm4 <- lmer(f0_CO2~treatment * plant + (1|date_short) + (1|chamber), data=select_fluxes_combined_w_T0, REML=FALSE)

co2.lm5 <- lmer(f0_CO2~ history + plant + (1|date_short) + (1|chamber), data=select_fluxes_combined_w_T0, REML=FALSE)

#co2.lm6 <- lmer(f0_CO2 ~ (1|chamber) , data=select_fluxes_combined_w_T0, REML=FALSE)

#co2.lm7 <- lmer(f0_CO2 ~ (1|date_short), data=select_fluxes_combined_w_T0, REML=FALSE)

co2.lm8 <- lmer(f0_CO2~ treatment + history + plant + (1|date_short) + (1|chamber), data=select_fluxes_combined_w_T0, REML=FALSE)

co2.lm9 <- lmer(f0_CO2~ history + (1|date_short) + (1|chamber), data=select_fluxes_combined_w_T0, REML=FALSE)

co2.lm10 <- lmer(f0_CO2~ plant+ treatment + (1|date_short) + (1|chamber), data=select_fluxes_combined_w_T0, REML=FALSE)

co2.lm11 <- lmer(f0_CO2~ plant* history + (1|date_short) + (1|chamber), data=select_fluxes_combined_w_T0, REML=FALSE)

co2.lm12 <- lmer(f0_CO2~ treatment +history + (1|date_short) + (1|chamber), data=select_fluxes_combined_w_T0, REML=FALSE)

#This is a likelihood ratio test to get Chi squared value and p-value
##a <- anova(co2.lm1, co2.lm2, co2.lm3,co2.lm4,co2.lm5, co2.lm6, co2.lm7, co2.lm8, co2.lm9, co2.lm4a, co2.lm7a, co2.lm8a)
##a
##anova(co2.lm6)

#AIC weights
c.mod <- list(co2.lm1, co2.lm2, co2.lm3,co2.lm4,co2.lm5, co2.lm8, co2.lm9, co2.lm10, co2.lm11, co2.lm12)
Modnames <- c("null", "treatment", "plant", "T*P", "H+P", "P+T+H", "H", "P+T", "P*H", "T+H")
co2_LME_RES <-aictab(cand.set = c.mod, modnames = Modnames, second.ord = TRUE)

# Gas ID for merging
co2_LME_RES$GHG <- "CO2"

#Variance explained by fixed effects and the entire model
r.squaredGLMM(co2.lm1) #null
r.squaredGLMM(co2.lm2) #treatment
r.squaredGLMM(co2.lm3) #plant
r.squaredGLMM(co2.lm4) #t * p
r.squaredGLMM(co2.lm5) #h + p
#r.squaredGLMM(co2.lm6) #chamber
#r.squaredGLMM(co2.lm7) #date
r.squaredGLMM(co2.lm8) #p+t+h
r.squaredGLMM(co2.lm9) #h
r.squaredGLMM(co2.lm10)#p+t
r.squaredGLMM(co2.lm11) #p*h
r.squaredGLMM(co2.lm12) #h+t

summary(co2.lm4, ddf="Kenward-Roger")
confint.merMod(co2.lm4, oldNames = FALSE)
p=profile(co2.lm4)
xyplot(p)
densityplot(p)
qqPlot(resid(co2.lm4), main="QQ Plot")
shapiro.test(resid(co2.lm4))

#Post hoc Tests
#Estimated marginal means - similar to lsmeans, uses t distribution
#https://cran.rstudio.com/web/packages/emmeans/vignettes/interactions.html

emm <- emmeans(co2.lm4, ~ plant*treatment , adjust = "sidak")
pairs(emm)
multcomp::cld(emm, Letters=letters)
```

```{r n2o hypothesis testing}
n2o.lm1 <- lmer(f0_N2O ~ (1|date_short) + (1|chamber) , data=select_fluxes_combined_w_T0, REML=FALSE)

n2o.lm2 <- lmer(f0_N2O~treatment + (1|date_short) + (1|chamber), data=select_fluxes_combined_w_T0, REML=FALSE)

n2o.lm3 <- lmer(f0_N2O~plant + (1|date_short) + (1|chamber), data=select_fluxes_combined_w_T0, REML=FALSE)

n2o.lm4 <- lmer(f0_N2O~treatment * plant + (1|date_short) + (1|chamber), data=select_fluxes_combined_w_T0, REML=FALSE)

n2o.lm5 <- lmer(f0_N2O~ history + plant + (1|date_short) + (1|chamber), data=select_fluxes_combined_w_T0, REML=FALSE)

#n2o.lm6 <- lmer(f0_N2O ~ (1|chamber) , data=select_fluxes_combined_w_T0, REML=FALSE)

#n2o.lm7 <- lmer(f0_N2O ~ (1|date_short), data=select_fluxes_combined_w_T0, REML=FALSE)

n2o.lm8 <- lmer(f0_N2O~ treatment + history + plant + (1|date_short) + (1|chamber), data=select_fluxes_combined_w_T0, REML=FALSE)

n2o.lm9 <- lmer(f0_N2O~ history + (1|date_short) + (1|chamber), data=select_fluxes_combined_w_T0, REML=FALSE)

n2o.lm10 <- lmer(f0_N2O~ plant + treatment + (1|date_short) + (1|chamber), data=select_fluxes_combined_w_T0, REML=FALSE)

n2o.lm11 <- lmer(f0_N2O~ plant * history + (1|date_short) + (1|chamber), data=select_fluxes_combined_w_T0, REML=FALSE)

n2o.lm12 <- lmer(f0_N2O~ history + treatment + (1|date_short) + (1|chamber), data=select_fluxes_combined_w_T0, REML=FALSE)

#This is a liklihood ratio test to get Chi squared value and p-value
##a <- anova(n2o.lm1, n2o.lm2, n2o.lm3,n2o.lm4,n2o.lm5, n2o.lm6, n2o.lm7, n2o.lm8, n2o.lm9, n2o.lm4a, n2o.lm7a, n2o.lm8a)
##a
##anova(n2o.lm6)

#AIC weights
c.mod <- list(n2o.lm1, n2o.lm2, n2o.lm3,n2o.lm4,n2o.lm5, n2o.lm8, n2o.lm9, n2o.lm10, n2o.lm11, n2o.lm12)
Modnames <- c("null", "treatment", "plant", "T*P", "H+P", "P+T+H", "H", "P+T", "P*H", "T+H")
n2o_LME_RES <- aictab(cand.set = c.mod, modnames = Modnames, second.ord = TRUE)

# For merging, at 'N2O' column:
n2o_LME_RES$GHG <- "N2O"

#Variance explained by fixed effects and the entire model
r.squaredGLMM(n2o.lm1) #null
r.squaredGLMM(n2o.lm2) #treatment
r.squaredGLMM(n2o.lm3) #plant
r.squaredGLMM(n2o.lm4) #t * p
r.squaredGLMM(n2o.lm5) #h + p
#r.squaredGLMM(n2o.lm6) #chamber
#r.squaredGLMM(n2o.lm7) #date
r.squaredGLMM(n2o.lm8) #p+t+h
r.squaredGLMM(n2o.lm9) #h
r.squaredGLMM(n2o.lm10) #p+t
r.squaredGLMM(n2o.lm11) #p*h
r.squaredGLMM(n2o.lm12)#h+t

summary(n2o.lm10, ddf="Kenward-Roger")
confint.merMod(n2o.lm10, oldNames = FALSE)
p=profile(n2o.lm10)
xyplot(p)
densityplot(p)
qqPlot(resid(n2o.lm10), main="QQ Plot")
shapiro.test(resid(n2o.lm10))

emm <- emmeans(co2.lm10, ~ plant + treatment , adjust = "sidak")
 pairs(emm)
 multcomp::cld(emm, Letters=letters)
```

```{r combined LME datatframe}
LME_comb <- rbind(ch4_LME_RES, co2_LME_RES, n2o_LME_RES)


ch4_R2s <- rbind(
r.squaredGLMM(ch4.lm1), #null
r.squaredGLMM(ch4.lm2), #treatment
r.squaredGLMM(ch4.lm3), #plant
r.squaredGLMM(ch4.lm4), #t * p
r.squaredGLMM(ch4.lm5), #h + p
#r.squaredGLMM(ch4.lm6) #chamber
#r.squaredGLMM(ch4.lm7) #date
r.squaredGLMM(ch4.lm8),#p+t+h
r.squaredGLMM(ch4.lm9), #h
r.squaredGLMM(ch4.lm10),#p+t
r.squaredGLMM(ch4.lm11),#p*h
r.squaredGLMM(ch4.lm12))#h+t

co2_R2s <- rbind(
r.squaredGLMM(co2.lm1), #null
r.squaredGLMM(co2.lm2), #treatment
r.squaredGLMM(co2.lm3), #plant
r.squaredGLMM(co2.lm4), #t * p
r.squaredGLMM(co2.lm5), #h + p
#r.squaredGLMM(co2.lm6) #chamber
#r.squaredGLMM(co2.lm7) #date
r.squaredGLMM(co2.lm8),#p+t+h
r.squaredGLMM(co2.lm9), #h
r.squaredGLMM(co2.lm10),#p+t
r.squaredGLMM(co2.lm11),#p*h
r.squaredGLMM(co2.lm12))#h+t

n2o_R2s <- rbind(
r.squaredGLMM(n2o.lm1), #null
r.squaredGLMM(n2o.lm2), #treatment
r.squaredGLMM(n2o.lm3), #plant
r.squaredGLMM(n2o.lm4), #t * p
r.squaredGLMM(n2o.lm5), #h + p
#r.squaredGLMM(n2o.lm6) #chamber
#r.squaredGLMM(n2o.lm7) #date
r.squaredGLMM(n2o.lm8),#p+t+h
r.squaredGLMM(n2o.lm9), #h
r.squaredGLMM(n2o.lm10),#p+t
r.squaredGLMM(n2o.lm11),#p*h
r.squaredGLMM(n2o.lm12))#h+t

# Convert to data frame:
ch4_R2s <- as.data.frame(ch4_R2s)
co2_R2s <- as.data.frame(co2_R2s)
n2o_R2s <- as.data.frame(n2o_R2s)

# Label GHGs again to confirm rbind happens correctly:
ch4_R2s$GHG <- c("CH4", "CH4", "CH4", "CH4", "CH4", "CH4", "CH4", "CH4", "CH4", "CH4")
co2_R2s$GHG <- c("CO2","CO2","CO2","CO2", "CO2", "CO2", "CO2", "CO2", "CO2", "CO2")
n2o_R2s$GHG <- c("N2O","N2O","N2O","N2O","N2O","N2O","N2O","N2O","N2O","N2O")

# Add Modnames to R2 data frames:
ch4_R2s$Modnames <- c("null", "treatment", "plant", "T*P", "H+P", "P+T+H", "H", "P+T", "P*H", "T+H")
co2_R2s$Modnames <- c("null", "treatment", "plant", "T*P", "H+P", "P+T+H", "H", "P+T", "P*H", "T+H")
n2o_R2s$Modnames <- c("null", "treatment", "plant", "T*P", "H+P", "P+T+H", "H", "P+T", "P*H", "T+H")
  
# Combine R2 data frames:
LME_R2s_comb <- rbind(ch4_R2s, co2_R2s, n2o_R2s) 

# all together:
LME_RESULTS <- full_join(LME_comb, LME_R2s_comb, by = c("Modnames", "GHG"))

# write.csv:
#write.csv(LME_RESULTS, file = "../figures/pub/tables/LME_results.csv", row.names = T)
```



