---
title: evaluating relationship between soil carbon dioxide flux and concentration at T1
author: "Ariane L. Peralta, Colin Finlay"
date: "Last updated on `r format(Sys.time(), '%d %B, %Y')`"
#output:
  #pdf_document: null
  #editor_options: null
  #fig_caption: yes
  #html_document: default
  #word_document: default
  #chunk_output_type: 
---
Project Description: Analysis of monthly greenhouse gas production in a fertilized coastal plain wetland (Greenville, NC, USA).

```{r setup, include=FALSE}
#clears R environment
rm(list = ls())
#use to set global options for chunks e.g., echo and warning options will be applied to all chunks
knitr::opts_chunk$set(echo = FALSE, warning=FALSE)
#use to set working directory 
knitr::opts_knit$set(root.dir="../GitHub/WRC_GHG/analyses")
#list.files()
```

```{r setup load packages}
setwd("~/GitHub/WRC_GHG/analyses")
#load requires packages
require("ggplot2")
require("tidyverse")
require("ggpmisc")
```

```{r read in ghg and environmental data}
#ghg flux data measured values
ghg_reg <- read.csv("../data/WRC_GHG_summer_2022.csv", header=T)
str(ghg_reg)
ghg_reg$TRT <- as.factor(ghg_reg$TRT)
ghg_reg$DITCH <- as.factor(ghg_reg$DITCH)
ghg_reg$Sample.Date <- as.factor(ghg_reg$Sample.Date)
str(ghg_reg)
```

```{r plot formatting}
#subset
ghg_reg_MU <-ghg_reg[ghg_reg$TRT == 'MU',]
dim(ghg_reg)
dim(ghg_reg_MU)

ghg_reg_MU_wet <-ghg_reg_MU[ghg_reg_MU$DITCH == 0,]
dim(ghg_reg_MU_wet)

ghg_reg_MU_dry <-ghg_reg_MU[ghg_reg_MU$DITCH == 1,]
dim(ghg_reg_MU_dry)

ghg_reg_MF <-ghg_reg[ghg_reg$TRT == 'MF',]
dim(ghg_reg)
dim(ghg_reg_MF)

```

```{r CO2 by month - unfert, echo=T, out.width="100%"}
p <- ggplot(ghg_reg_MU) + geom_point(aes(x=T1, y=Soil.Flux2, shape=DITCH, color=Sample.Date), size=3) 

CO2_reg_MU <- p + theme_bw() + 
    theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.line 
          =element_line(colour = "black")) + 
    theme(axis.title=element_text(vjust=1,size=14,face="bold"),
          axis.text=element_text(size=14), axis.text.x = element_text(vjust=0.65, hjust=0.5, angle=45, 
          size=14), panel.border = element_rect(colour = "black",size=1)) + 
    theme(axis.ticks.length=unit(0.3,"cm")) + 
          labs(x = "Concentration (ppm-v)", y = (expression(paste("CO"[2], " fluxes (grams C"," m"^-{2}," day"^-{1},")")))) + 
    theme(strip.text.x = element_text(size=14, face="bold"), 
          strip.text.y = element_text(size=14, face="bold"), 
          strip.background = element_rect(colour="black", fill="white", size=1)) + 
    ggtitle("Relationship between carbon dioxide fluxes and concentrations at T1") + 
            theme(plot.title = element_text(face = "italic"))
CO2_reg_MU
#ggsave("../figures/CO2_flux_by_conc_UNFERT.png", plot=CO2_reg_MU, device=NULL, path=NULL, scale=1, width=10, height=4, dpi=300, limitsize=TRUE)

CO2_reg_MU_model <- lm(Soil.Flux2~T1, data=ghg_reg_MU)
summary(CO2_reg_MU_model)

```

```{r CO2 by month - unfert wet only, echo=T, out.width="100%"}
p <- ggplot(ghg_reg_MU_wet) + geom_point(aes(x=T1, y=Soil.Flux2, color=Sample.Date), size=3) 

CO2_reg_MU_wet <- p + theme_bw() + 
    theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.line 
          =element_line(colour = "black")) + 
    scale_color_manual(name="Sample Month", 
                       values=c("#cc79a7", "#0072b2", "#f0e442", "#009e73"), 
                       labels = c("August 2022","July 2022", "June 2022", "May 2022")) +
    theme(axis.title=element_text(vjust=1,size=14,face="bold", margin=margin(r=10)),
          axis.text=element_text(size=14), axis.text.x = element_text(vjust=0.65, hjust=0.5, angle=0, 
          size=14), panel.border = element_rect(colour = "black",size=1)) + 
    theme(axis.ticks.length=unit(0.3,"cm")) + 
          labs(x = "Concentration (ppm)", y = (expression(paste("CO"[2], " fluxes (grams C"," m"^-{2}," day"^-{1},")")))) + 
    theme(strip.text.x = element_text(size=14, face="bold"), 
          strip.text.y = element_text(size=14, face="bold"), 
          strip.background = element_rect(colour="black", fill="white", size=1))+
  stat_poly_eq(aes(x=T1, y=Soil.Flux2, label = paste(after_stat(f.value.label), after_stat(adj.rr.label), after_stat(p.value.label), sep = "*\", \"*")), data = ghg_reg_MU_wet, formula = y ~ x, method = "lm", label.y = "top",label.x = "left")+
   geom_smooth(aes(x=T1, y=Soil.Flux2), formula = y ~ x, method=lm, se=T, color="black")

CO2_reg_MU_wet

#ggsave("../figures/pub//CO2_flux_by_conc_UNFERT_wet.tiff", plot=CO2_reg_MU_wet, device="tiff", path=NULL, scale=1, width=6, height=4, dpi=300, limitsize=TRUE)

CO2_reg_MU_wet_model <- lm(Soil.Flux2~T1, data=ghg_reg_MU_wet)
summary(CO2_reg_MU_wet_model)

```
```{r CO2 by month - unfert dry only, echo=T, out.width="100%"}
p <- ggplot(ghg_reg_MU_dry) + geom_point(aes(x=T1, y=Soil.Flux2, color=Sample.Date), size=3) 

CO2_reg_MU_dry <- p + theme_bw() + 
    theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.line 
          =element_line(colour = "black")) + 
    theme(axis.title=element_text(vjust=1,size=14,face="bold"),
          axis.text=element_text(size=14), axis.text.x = element_text(vjust=0.65, hjust=0.5, angle=45, 
          size=14), panel.border = element_rect(colour = "black",size=1)) + 
    theme(axis.ticks.length=unit(0.3,"cm")) + 
          labs(x = "Concentration (ppm)", y = (expression(paste("CO"[2], " fluxes (grams C"," m"^-{2}," day"^-{1},")")))) + 
    theme(strip.text.x = element_text(size=14, face="bold"), 
          strip.text.y = element_text(size=14, face="bold"), 
          strip.background = element_rect(colour="black", fill="white", size=1)) + 
    ggtitle("Relationship between carbon dioxide fluxes and concentrations at T1") + 
            theme(plot.title = element_text(face = "italic"))

CO2_reg_MU_dry
#ggsave("../figures/CO2_flux_by_conc_UNFERT_drt.png", plot=CO2_reg_MU_dry, device=NULL, path=NULL, scale=1, width=10, height=4, dpi=300, limitsize=TRUE)

CO2_reg_MU_dry_model <- lm(Soil.Flux2~T1, data=ghg_reg_MU_dry)
summary(CO2_reg_MU_dry_model)

```
